name: test_release

on:
  push:
    branches:
      - 'test_*'
  workflow_dispatch:

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      deployments: write
      packages: none
      pull-requests: write
      security-events: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Set branch name
      run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Prepare scenarios to be released.
      run: |
        sudo apt install zip
        zip -r scenarios.zip scenarios

        languages=("de-DE" "es-ES" "fr-FR" "hu-HU" "id-ID" "it-IT" "ja-JP" "ko-KR" "nl-NL" "pl-PL" "pt-BR" "pt-PT" "ru-RU" "sv-SE" "tr-TR" "zh-CN" "zh-TW")
        for lang in "${languages[@]}"; do
          # Set the source directory
          src_dir="localized/$lang"
          # Set the destination zip file
          zip_file="${lang}-scenarios.zip"
          # Change to the source directory and create the zip file
          (cd "$src_dir" && zip -r "../../$zip_file" scenarios)
        done
    - name: Check for changes in 'Scenarios' folder
      id: check_changes
      run: |
        CHANGED=$(git diff --name-only HEAD^  HEAD -- scenarios)
        if [ -n "$CHANGED" ]; then
          echo "Changes detected in Scenarios folder."
          echo "scenarios_changed=true" >> $GITHUB_ENV
        else
          echo "No changes detected in Scenarios folder."
          echo "scenarios_changed=false" >> $GITHUB_ENV
        fi
    - name: Get count of successful runs
      id: get_count
      run: |
        # Replace `workflow_id` with your actual workflow file name or ID
        # Replace `your_token` with a GitHub token with appropriate permissions
        WORKFLOW_RUNS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/release.yml/runs?per_page=1")
        SUCCESS_COUNT=$(echo $WORKFLOW_RUNS | jq '.workflow_runs[0].run_number')
        echo "Total runs: $SUCCESS_COUNT"
        echo "success_count=$SUCCESS_COUNT" >> $GITHUB_ENV
    - name: Setup release
      if: env.scenarios_changed == 'true'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: t1.0.${{ env.success_count }}
        release_name: t1.0.${{ env.success_count }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./scenarios.zip
        asset_name: scenarios.zip
        asset_content_type: application/zip        
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cs-CZ-scenarios.zip
        asset_name: cs-cz-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./de-DE-scenarios.zip
        asset_name: de-de-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./es-ES-scenarios.zip
        asset_name: es-es-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./fr-FR-scenarios.zip
        asset_name: fr-fr-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hu-HU-scenarios.zip
        asset_name: hu-hu-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./id-ID-scenarios.zip
        asset_name: id-id-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./it-IT-scenarios.zip
        asset_name: it-it-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ja-JP-scenarios.zip
        asset_name: ja-jp-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ko-KR-scenarios.zip
        asset_name: ko-kr-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nl-NL-scenarios.zip
        asset_name: nl-nl-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pl-PL-scenarios.zip
        asset_name: pl-pl-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pt-BR-scenarios.zip
        asset_name: pt-br-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pt-PT-scenarios.zip
        asset_name: pt-pt-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ru-RU-scenarios.zip
        asset_name: ru-ru-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./sv-SE-scenarios.zip
        asset_name: sv-se-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./tr-TR-scenarios.zip
        asset_name: tr-tr-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zh-CN-scenarios.zip
        asset_name: zh-cn-scenarios.zip
        asset_content_type: application/zip
    - name: Upload Release Asset
      if: env.scenarios_changed == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zh-TW-scenarios.zip
        asset_name: zh-tw-scenarios.zip
        asset_content_type: application/zip
    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        PR_TITLE="Update from ${{ env.branch_name }} to main "
        PR_BODY="This PR merges changes from ${{ env.branch_name }} into the main branch. Please review the changes and merge if everything is in order."
        BASE_BRANCH="main" # The branch you want to merge into
        HEAD_BRANCH=${{ env.branch_name }} # The branch you want to merge from
    
        # Create the Pull Request
        RESPONSE=$(curl -s -X POST \
          -H "Authorization: token $PAT" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls" \
          -d "{\"title\":\"${PR_TITLE}\", \"body\":\"${PR_BODY}\", \"head\":\"${HEAD_BRANCH}\", \"base\":\"${BASE_BRANCH}\"}")
    
        # Extract the PR URL and output it
        PR_URL=$(echo $RESPONSE | jq -r .html_url)
        echo "Pull Request created: $PR_URL"